name: pre-commit
on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - uses: pre-commit/action@v3.0.1
        # opcjonalnie: uruchom tylko gitleaks
        # with: { extra_args: "gitleaks --all-files" }
